"""Canonical organizational memory and world-model contracts.

The Company Brain is the shared, governed substrate consumed by product
workflows. It contains facts and evidence; it does not grant action authority.
"""

from .model import (
    BrainEntity,
    BrainEvidence,
    BrainPrincipal,
    CompanyBrain,
    CompanyBrainContext,
    CompanyBrainError,
    EntityKind,
    RelationshipKind,
)
from .projector import (
    CompanyBrainProjector,
    ProjectionResult,
    repository_id,
    service_id,
)
from .store import (
    BrainAuditEvent,
    BrainProvenance,
    CompanyBrainRetentionError,
    CompanyBrainStore,
    CompanyBrainStoreError,
    CompanyBrainVersionConflict,
    RetentionPolicy,
    SqliteCompanyBrainStore,
    StoredEntity,
    StoredEvidence,
    StoredRelationship,
)
from .memory import (
    BrainProjectionJournal,
    BrainSourceProjection,
    CompanyBrainMemoryError,
    CompanyBrainMemoryProjector,
    ProjectionReceipt,
    ProjectionState,
    SqliteBrainProjectionJournal,
)
from .world_model import (
    CompanyBrainWorldModel,
    EntityQualification,
    EvidenceQualification,
    FactFreshness,
    QualifiedWorldModelContext,
    RelationshipQualification,
    SourceTrustRule,
    WorldModelConflict,
    WorldModelConflictKind,
    WorldModelError,
    WorldModelPolicy,
)
from .product_contracts import (
    EvidenceBasis,
    EvidenceBundle,
    EvidenceReference,
    FindingProvenance,
    ProductContractError,
    ProductFinding,
    ProductOutcome,
    ProductSubject,
)
from .feedback import CompanyBrainFeedbackProjector
from .maintenance import (
    CompanyBrainMaintenanceError,
    CompanyBrainMaintenanceReader,
    DEFAULT_MAINTENANCE_KINDS,
    MemoryMaintenanceAction,
    MemoryMaintenanceFindingKind,
    MemoryMaintenancePlan,
    MemoryMaintenancePolicy,
    MemoryMaintenanceProposal,
    plan_company_brain_maintenance,
)
from .maintenance_outcomes import (
    MaintenanceOutcome,
    MaintenanceOutcomeState,
    MaintenanceReviewDecision,
    MaintenanceReviewDisposition,
    SourceRevisionObservation,
    evaluate_maintenance_outcome,
    parse_maintenance_proposal,
    parse_maintenance_review_decision,
    parse_source_revision_observation,
)

__all__ = [
    "BrainEntity",
    "BrainEvidence",
    "BrainPrincipal",
    "CompanyBrain",
    "CompanyBrainContext",
    "CompanyBrainError",
    "EntityKind",
    "RelationshipKind",
    "CompanyBrainProjector",
    "ProjectionResult",
    "repository_id",
    "service_id",
    "BrainAuditEvent",
    "BrainProvenance",
    "CompanyBrainRetentionError",
    "CompanyBrainStore",
    "CompanyBrainStoreError",
    "CompanyBrainVersionConflict",
    "RetentionPolicy",
    "SqliteCompanyBrainStore",
    "StoredEntity",
    "StoredEvidence",
    "StoredRelationship",
    "BrainProjectionJournal",
    "BrainSourceProjection",
    "CompanyBrainMemoryError",
    "CompanyBrainMemoryProjector",
    "ProjectionReceipt",
    "ProjectionState",
    "SqliteBrainProjectionJournal",
    "CompanyBrainWorldModel",
    "EntityQualification",
    "EvidenceQualification",
    "FactFreshness",
    "QualifiedWorldModelContext",
    "RelationshipQualification",
    "SourceTrustRule",
    "WorldModelConflict",
    "WorldModelConflictKind",
    "WorldModelError",
    "WorldModelPolicy",
    "EvidenceBasis",
    "EvidenceBundle",
    "EvidenceReference",
    "FindingProvenance",
    "ProductContractError",
    "ProductFinding",
    "ProductOutcome",
    "ProductSubject",
    "CompanyBrainFeedbackProjector",
    "CompanyBrainMaintenanceError",
    "CompanyBrainMaintenanceReader",
    "DEFAULT_MAINTENANCE_KINDS",
    "MemoryMaintenanceAction",
    "MemoryMaintenanceFindingKind",
    "MemoryMaintenancePlan",
    "MemoryMaintenancePolicy",
    "MemoryMaintenanceProposal",
    "plan_company_brain_maintenance",
    "MaintenanceOutcome",
    "MaintenanceOutcomeState",
    "MaintenanceReviewDecision",
    "MaintenanceReviewDisposition",
    "SourceRevisionObservation",
    "evaluate_maintenance_outcome",
    "parse_maintenance_proposal",
    "parse_maintenance_review_decision",
    "parse_source_revision_observation",
]
